application: jamestoolmetrics 
version : 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: webapp2
    version: latest
  
  - name: jinja2
    version: latest
    
handlers:
  - url: /stylesheets
    static_dir: stylesheets
    
  - url: /js
    static_dir: js 
   

  - url : .*
    script: Main.application
  
  

